import type {NextPage} from "next";
import Head from "next/head";
import React from "react";

import BookList from "../components/BookList";
import styles from "../styles/Home.module.scss";

const Home: NextPage = (): JSX.Element => {
  const [name, setName] = React.useState<string>("Unknown");

  // const data = fetch("http://localhost:3000/api/hello/")
  //   .then((response) => response.json())
  //   .then((res) => setName(res.name));
  // console.log({data});
  setTimeout(() => {
    fetch("http://localhost:3000/api/name/")
      .then((response) => response.json())
      .then((res) => setName(res.name));
  }, 1000);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App_3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{textAlign: "center"}}>Next App_3</h1>
        <h2 style={{textAlign: "center"}}>Hello {name}</h2>
        <br />
        <BookList />
      </main>
    </div>
  );
};

export default Home;
